<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use App\Modules\Pages\Models\Invoice;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Support\Str;

class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'image',
        'nid',
        'cin',
        'referred_by',
        'email',
        'phone',
        'password',
        'phone_verified_at',
        'status',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    public function hasPermission($permission)
    {
        return $this->permissions()->where('name', $permission)->exists();
    }

    public function activeSubscription()
    {
        return $this->hasOne(Subscription::class)->where('status', 'active');
    }

    // The user who referred this user
    public function referrer()
    {
        return $this->belongsTo(User::class, 'referred_by');
    }

    // Users that this user has referred
    public function referrals()
    {
        return $this->hasMany(User::class, 'referred_by');
    }

    // My earned commissions
    public function commissions()
    {
        return $this->hasMany(Commission::class, 'user_id');
    }

    public function withdraws()
    {
        return $this->hasMany(Withdraw::class, 'user_id');
    }

    // Commissions generated by me for others
    public function generatedCommissions()
    {
        return $this->hasMany(Commission::class, 'from_user_id');
    }

    public function getWalletAttribute()
    {
        $totalCommission = $this->commissions()->sum('amount');

        $totalWithdraw = $this->withdraws()
            ->where('status', 'approved')
            ->sum('amount');

        return $totalCommission - $totalWithdraw;
    }

    protected static function booted()
    {
        static::creating(function ($customer) {
            if (empty($customer->cin)) {
                $customer->cin = self::generateCIN();
            }
        });
    }

    public static function generateCIN()
    {
        do {
            // Generate random 6-character alphanumeric string
            $cin = strtoupper(Str::random(8));
        } while (self::where('cin', $cin)->exists()); // Ensure uniqueness

        return $cin;
    }

    public function sendOTP()
    {
        $otp = Str::random(6);
        $this->otp = $otp;
        $this->save();
        return $otp;
    }

    public function invoices()
    {
        return $this->hasMany(Invoice::class, 'users_id');
    }
}
